# .goreleaser.yaml
builds:
  - id: livetv
    # Path to your main package (where your main() function is)
    main: ./ # Adjust this path based on your project structure
    binary: livetv
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    # Enable CGO if needed for this build
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -buildvcs=false
      
archives:
  - id: livetv_archive
    builds:
      - livetv 
    format: binary # Output as a raw binary file, not a tar.gz or zip
    # Define the name template for the output file
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ end }}"
    wrap_in_directory: true
    strip_binary_directory: true


