name: IPTV-Go

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - '**.go'    
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'

jobs:
  linux_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y gcc
      - name: Cross Compile with CGO
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
        run: go build -o livetv_linux_amd64 -ldflags="-linkmode external -extldflags '-lm -lsqlite3'"
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_linux_amd64
          path: livetv_linux_amd64

  linux_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y gcc
      - name: Cross Compile with CGO
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
        run: go build -o livetv_linux_arm64 -ldflags="-linkmode external -extldflags '-lm -lsqlite3'"
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_linux_arm64
          path: livetv_linux_arm64

  darwin_amd64_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc
        run: brew install gcc
      - name: Cross Compile with CGO
        env:
          CGO_ENABLED: 1
          GOOS: darwin
          GOARCH: amd64
        run: go build -o livetv_darwin_amd64 -ldflags="-linkmode external -extldflags '-lm -lsqlite3'"
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_darwin_amd64
          path: livetv_darwin_amd64

  darwin_arm64_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc
        run: brew install gcc
      - name: Cross Compile with CGO
        env:
          CGO_ENABLED: 1
          GOOS: darwin
          GOARCH: arm64
        run: go build -o livetv_darwin_arm64 -ldflags="-linkmode external -extldflags '-lm -lsqlite3'"
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_darwin_arm64
          path: livetv_darwin_arm64
  
  windows_amd64_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc (MinGW)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MSYS
          packages: mingw-w64-x86_64-gcc
      - name: Cross Compile with CGO
        env:
          CGO_ENABLED: 1
          GOOS: windows
          GOARCH: amd64
        run: go build -o livetv_windows_amd64.exe -ldflags="-linkmode external -extldflags '-lm -lsqlite3'"
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_windows_amd64
          path: livetv_windows_amd64.exe    
