name: IPTV-Go

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - '**.go'    
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'

jobs:
  linux_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLite Development Libraries
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Set up Go environment with CGO enabled
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'
          cache: 'true'  # 修改为布尔类型 'true'
        env:
          CGO_ENABLED: '1'

      - name: Cross Compile
        run: |
          export CGO_ENABLED=1
          GOOS=linux GOARCH=amd64 go build -o livetv_linux_amd64

      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_linux_amd64
          path: livetv_linux_amd64

  # 其他构建任务（如 linux_arm64_build, darwin_amd64_build 等）类似地修改 `cache` 字段
  linux_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLite Development Libraries
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Set up Go environment with CGO enabled
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'
          cache: 'true'  # 修改为布尔类型 'true'
        env:
          CGO_ENABLED: '1'

      - name: Cross Compile
        run: |
          export CGO_ENABLED=1
          GOOS=linux GOARCH=arm64 go build -o livetv_linux_arm64

      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: livetv_linux_arm64
          path: livetv_linux_arm64
