name: Build and Release Go Binaries

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
  push:
    branches: ["main"]
    paths:
      - '**.go'
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: goreleaser_build
    name: ${{ matrix.job_name }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed by GoReleaser for git information

      - name: Set up Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Run GoReleaser for Cross-Compilation
        uses: goreleaser/goreleaser-action@v3
        with:
          version: ${{ github.event.inputs.tag }}
          ldflags: "-s -w -X main.version=${{ github.event.inputs.tag }}"
          targets: ["bin"]
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  cleanup:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5
